name: Print Hello World

on:
  push:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello World"

  second-job:
    runs-on: ubuntu-latest
    needs: say-hello   # 👈 runs AFTER say-hello finishes

    steps:
      - name: Print Second Job
        run: echo "Second job executed after Hello World"
